### ISSUE TITLE
Issue with PDF files

### ISSUE THREAD

**Issue by leslie3982** [GladistonXD/perlego-download#14]
Hi Team, thanks for your extension. It works well with epub files. But when I was trying with pdf books, it seems not to regconize the pages at all. 

I received this popup message ("Page 0/null found"). Although I tried to load the page to the bottom, it does not work (I also tried with Chrome portable as you suggested in previous closed issues).

![Screenshot 2024-07-13 120745](https://github.com/user-attachments/assets/607fcd87-74e2-4eb0-be3a-f0098eb39383)

Do you have any ideas to fix this issue? Any guidance from you will be of much help. Thanks in advance!

**Comment by GladistonXD** [comment]
Probably the site changed something, I'll release a correction later

**Comment by GladistonXD** [comment]
Apparently everything is normal, your problem must be because the counter is not displayed on the screen, try running in full screen or zoom out the page until the counter appears in the bottom right corner
![image](https://github.com/user-attachments/assets/0455078f-1e8d-4b9a-810c-e8a17ef39111)

This paging counter

**Comment by leslie3982** [comment]
Yass that was super helpful. I've already succeeded in downloading the file. Many thanks for the prompt reply.

Have a nice day!
